### ISSUE TITLE
Mod still not working as of 1.1.1; rollback to 1.0.0 still functions

### ISSUE THREAD

**Issue by keriugi** [kitty-girl/webfishingmods#2]
as detailed in the previous issue, the customize button has disappeared and no effects of the mod are visible, even after updating from 1.1.0 to 1.1.1

the mod appears to have loaded and is visible in tacklebox with no errors given.

**Comment by kitty-girl** [comment]
actually fixed in v1.1.2 my bad

**Comment by keriugi** [comment]
it does seem to be fixed! it's an excellent mod and your work is really appreciated.
